services:
    database:
        build:
            dockerfile_inline: |
                FROM mysql:5.7

                RUN touch /startup_log.txt
                RUN chown mysql:mysql /startup_log.txt
                RUN sed -i -E 's,(^\s*printf .*$),\1 | tee -a /startup_log.txt,' /usr/local/bin/docker-entrypoint.sh
                RUN sed -i -E 's,(^\s*)(exec "\$@"),\1mysql_note "STARTING_UP"\n\1\2,' /usr/local/bin/docker-entrypoint.sh

                CMD ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8", "--collation-server=utf8_general_ci", "--lower_case_table_names=1", "--log_warnings=1"]
        container_name: "${NAMESPACE}-database-mysql"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_DATABASE=${DATABASE_NAME}
        healthcheck:
            retries: 10
            start_period: 5m
            test: "mysqladmin ping -h localhost && grep 'STARTING_UP' /startup_log.txt"
            timeout: 20s
        ports:
            - "3307:3306"
        ulimits:
            nofile:
                hard: 40000
                soft: 20000
            nproc: 65535
        volumes:
            - read_only: true
              source: data-volume
              target: /docker-entrypoint-initdb.d
              type: volume
              volume:
                  subpath: dumps
            - source: data-volume
              target: /var/lib/mysql
              type: volume
              volume:
                  subpath: container-data/mysql
    liferay:
        depends_on:
            database:
                condition: service_healthy
        environment:
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root