services:
    database:
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1 --log_warnings=1
        container_name: "${NAMESPACE}-database-mysql"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_DATABASE=${DATABASE_NAME}
        healthcheck:
            retries: 10
            test: "mysqladmin ping -h localhost"
            timeout: 20s
        image: mysql:5.7
        ports:
            - "3306:3306"
    liferay:
        depends_on:
            database:
                condition: service_healthy
        environment:
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8
            - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root