name: "${NAMESPACE}"
services:
    data-helper:
        build:
            context: helper
            dockerfile: ../Dockerfile.helper
        container_name: ${NAMESPACE}-data-helper
        volumes:
            - data-volume:/data
volumes:
    data-volume: