services:
    data-helper:
        volumes:
            -   webserver-http:/container-data/webserver-http
    webserver:
        build: ./compose-recipes/webserver-http
        container_name: ${NAMESPACE}-webserver-http
        depends_on:
            liferay:
                condition: service_healthy
        ports:
            -   "80:80"
        volumes:
            -   webserver-http:/etc/nginx/conf.d
volumes:
    webserver-http: